# Generated by Django 5.0.3 on 2024-04-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="departments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_id", models.CharField(max_length=500, unique=True)),
                ("dept_name", models.CharField(max_length=500)),
                ("hod", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="subjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_code", models.CharField(max_length=500, unique=True)),
                ("subject_name", models.CharField(max_length=500)),
                ("semester", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="vanue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vanue_name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Facultydetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_id", models.CharField(max_length=30, unique=True)),
                ("faculty_name", models.CharField(max_length=500)),
                ("date_of_birth", models.DateField()),
                ("designation", models.CharField(max_length=500)),
                ("expertise", models.CharField(max_length=500)),
                ("qualification", models.CharField(max_length=500)),
                ("join_date", models.DateField()),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=500)),
                ("zipcode", models.IntegerField(unique=True)),
                ("username", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=500)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.departments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="time_table_field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("division", models.CharField(max_length=500)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.departments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="time_table_subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=500)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("faculty", models.ManyToManyField(to="app1.facultydetail")),
                ("subject", models.ManyToManyField(to="app1.subjects")),
                (
                    "time_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.time_table_field",
                    ),
                ),
            ],
        ),
    ]
