# Generated by Django 5.0.2 on 2024-02-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app1', '0002_department_subject_rename_teacher_vanue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_id',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
