# Generated by Django 5.0.3 on 2024-04-30 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_rename_day_time_table_subject_week_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="time_table_subject",
            old_name="end_time",
            new_name="ends_time",
        ),
    ]
