# Generated by Django 4.1 on 2024-02-22 16:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_department_dept_id_department_hod"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="department",
            new_name="departments",
        ),
    ]
