# Generated by Django 4.1 on 2024-02-22 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_rename_department_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="gender",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
