# Generated by Django 4.1 on 2024-02-22 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_faculty_gender"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="subject",
            new_name="subjects",
        ),
    ]
