# Generated by Django 4.1 on 2024-02-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_rename_subject_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="faculty_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
