# Generated by Django 4.1 on 2024-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0007_alter_faculty_faculty_id_alter_faculty_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="faculty_id",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="phone",
            field=models.CharField(max_length=500),
        ),
    ]
