# Generated by Django 4.1 on 2024-03-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_alter_faculty_faculty_id_alter_faculty_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facultydetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty_id", models.CharField(max_length=30)),
                ("faculty_name", models.CharField(max_length=500)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=500)),
                ("designation", models.CharField(max_length=500)),
                ("expertise", models.CharField(max_length=500)),
                ("qualification", models.CharField(max_length=500)),
                ("join_date", models.DateField()),
                ("address", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=500)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=500)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.departments",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="faculty",
        ),
    ]
