# Generated by Django 5.0.3 on 2024-03-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_facultydetail_delete_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultydetail",
            name="username",
            field=models.CharField(default="default_username", max_length=255),
        ),
        migrations.AlterField(
            model_name="departments",
            name="dept_id",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="subjects",
            name="subject_code",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
