# Generated by Django 5.0.3 on 2024-03-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0010_facultydetail_username_alter_departments_dept_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultydetail",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
