# Generated by Django 5.0.3 on 2024-03-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0011_alter_facultydetail_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultydetail",
            name="city",
            field=models.CharField(default="Ahmedabad", max_length=255),
        ),
        migrations.AddField(
            model_name="facultydetail",
            name="country",
            field=models.CharField(default="India", max_length=255),
        ),
        migrations.AddField(
            model_name="facultydetail",
            name="state",
            field=models.CharField(default="Gujarat", max_length=255),
        ),
    ]
