# Generated by Django 5.0.3 on 2024-03-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0012_facultydetail_city_facultydetail_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultydetail",
            name="zipcode",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="facultydetail",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="facultydetail",
            name="country",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="facultydetail",
            name="state",
            field=models.CharField(max_length=255),
        ),
    ]
