# Generated by Django 5.0.3 on 2024-03-29 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0015_alter_facultydetail_city_alter_facultydetail_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facultydetail",
            name="gender",
        ),
    ]
