# Generated by Django 5.0.3 on 2024-03-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0016_remove_facultydetail_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="departments",
            name="no_of_student",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="facultydetail",
            name="faculty_id",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
