# Generated by Django 5.0.3 on 2024-03-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0017_departments_no_of_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="no_of_student",
            field=models.IntegerField(),
        ),
    ]
