# Generated by Django 5.0.3 on 2024-03-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0018_alter_departments_no_of_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departments",
            name="no_of_student",
        ),
        migrations.AlterField(
            model_name="facultydetail",
            name="faculty_id",
            field=models.CharField(max_length=30),
        ),
    ]
