# Generated by Django 5.0.3 on 2024-04-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0019_remove_departments_no_of_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("division", models.CharField(max_length=500)),
            ],
        ),
    ]
