# Generated by Django 5.0.3 on 2024-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0020_timetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultydetail",
            name="faculty_id",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="facultydetail",
            name="zipcode",
            field=models.IntegerField(unique=True),
        ),
    ]
