# Generated by Django 5.0.3 on 2024-04-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0021_alter_facultydetail_faculty_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultydetail",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
