# Generated by Django 5.0.3 on 2024-04-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0022_alter_facultydetail_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="day",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetable",
            name="duration",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetable",
            name="end_date",
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetable",
            name="faculty",
            field=models.ManyToManyField(to="app1.facultydetail"),
        ),
        migrations.AddField(
            model_name="timetable",
            name="start_date",
            field=models.DateField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetable",
            name="status",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetable",
            name="subject",
            field=models.ManyToManyField(to="app1.subjects"),
        ),
        migrations.AddField(
            model_name="timetable",
            name="time",
            field=models.TimeField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timetable",
            name="vanue",
            field=models.ManyToManyField(to="app1.vanue"),
        ),
    ]
